name: Build and test

on:
  workflow_dispatch:

  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build source code
        run: ./gradlew build -x test

      - name: Run tests
        id: run-tests
        run: ./gradlew test >./test-res-out.log 2>./test-res-err.log
        continue-on-error: true

      - name: Display test results
        run: python ./scripts/test-result-printer.py -d ./lib/build/test-results/test
        continue-on-error: true
      
      - name: Run jacoco tests coverage report creating
        if: ${{ steps.run-tests.outcome == 'success' }}
        run: ./gradlew jacocoTestReport >./test-res-out.log 2>./test-res-err.log
        continue-on-error: true

      - name: Display info about coverage
        if: ${{ steps.run-tests.outcome == 'success' }}
        run: python3 ./scripts/csv-reports-printer.py -i ./lib/build/reports/jacoco/info.csv -l lib
        continue-on-error: true

      - name: Clearing tmpfiles of test runnig
        run: rm ./test-res-out.log && rm ./test-res-err.log
