name: Build and test

on:
  workflow_dispatch:

  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build source code
        run: ./gradlew build -x test

      - name: Run tests with jacoco
        run: ./gradlew test

      - name: Display info about coverage
        run: python3 ./scripts/csv-reports-printer.py -i ./lib/build/reports/jacoco/info.csv -l lib
